# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-16 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0044_auto_20200514_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiaryProposal',
            fields=[
                ('proposal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='disturbance.Proposal')),
            ],
            bases=('disturbance.proposal',),
        ),
    ]
