# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-14 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0217_auto_20210205_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelOptions(
            name='systemmaintenance',
            options={},
        ),
    ]
